export enum ActivityType {
  WORKSPACE_CREATED = "WORKSPACE_CREATED",
  WORKSPACE_UPDATED = "WORKSPACE_UPDATED",
  WORKSPACE_DELETED = "WORKSPACE_DELETED",
  MEMBER_ADDED = "MEMBER_ADDED",
  MEMBER_REMOVED = "MEMBER_REMOVED",
  MEMBER_ROLE_CHANGED = "MEMBER_ROLE_CHANGED",
  BOARD_CREATED = "BOARD_CREATED",
  BOARD_UPDATED = "BOARD_UPDATED",
  BOARD_DELETED = "BOARD_DELETED",
  BOARD_CONTENT_CHANGED = "BOARD_CONTENT_CHANGED",
}
